### PR TITLE
TODO React App

### PR DESCRIPTION
**Pull request by iAmWaris97**
- Followed the tutorials.
- Developed the App following the documentation.
- Brought changes in the Style.
- Add, Remove, Update and mark as completed functionalities are working well.

### CODE REVIEW

**Review by OmarMWarraich — COMMENTED** [review]
# Invalid ❌

Hi @iAmWaris97  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] As per this [requirment](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/exercises/full_partner_review.md), Please make sure that Linter should be set up correctly for this repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by iAmWaris97** [comment]
@OmarMWarraich,

Thank you for your kind review,
I have made the requested changes, please review them anytime you are free.

**Comment by iAmWaris97** [comment]
@OmarMWarraich,

Thank you for your kind review,
I have made the requested changes, please review them anytime you are free.

**Review by OmarMWarraich — APPROVED** [review]
## Hi @iAmWaris97  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
